from selenium.webdriver.common.by import By

from Configurations.config import Testdata
from Pageobjects.Basepage import Basepage
from Pageobjects.Homepage import Homepage

"""By locators"""


class SettingsPage(Basepage):
    SETTINGS_BUTTON = (By.ID, "navbar-settings")
    FIRST_NAME_FIELD = (By.ID, "profile_details_first_name")
    LAST_NAME_FIELD = (By.ID, "profile_details_last_name")
    SELECT_COUNTRY_FLAG = (By.ID, "")
    CONTACT_NUMBER_FIELD = (By.ID, "profile_details_contact_number")
    SUBMIT_BUTTON = (By.ID, "submitbutton_account")
    CANCEL_BUTTON = (By.ID, "cancelbutton_account")
    ORGANIZATION_SETTINGS_TAB = (By.ID, "org-settings-2")
    ORGANIZATION_NAME_FIELD = (By.ID, "organisation_name")
    ORGANIZATION_EMAIL_FIELD = (By.ID, "organisation_mail_id")
    ORGANIZATION_WEBSITE_LINK_FIELD = (By.ID, "organisation_website_link")
    ORGANIZATION_CONTACTNUMBER_FIELD = (By.ID, "organisation_contact_number")
    ORGANIZATION_ADDRESS_FIELD = (By.ID, "organisation_address")
    COUNTRY_FIELD = (By.ID, "country_select")
    SELECT_COUNTRY = (By.XPATH, "//li[text()='India']")
    ORGANIZATION_PINCODE_FIELD = (By.ID, "organisation_pin_code")
    ORGANIZATION_DESCRIPTION_FIELD = (By.ID, "organisation_description")
    UPLOAD_ORGANIZATION_LOGO= (By.ID,"file-upload-drag-and-drop-org-upload-file")
    CANCEL_LOGO_BUTTON = (By.ID,"cancel-uploaded-file")
    DONE_BUTTON_LOGO = (By.ID,"crop-image-preview-done-btn")
    ORGANIZATION_SUBMIT_BUTTON = (By.ID, "submitbutton_org")
    POLICY_TAB = (By.ID, "policy-settings-3")
    ADD_NEW_POLICY = (By.ID, "addnew-policy-button")
    POLICY_NAME_FIELD = (By.ID, "policyName")
    POLICY_DESCRIPTION = (By.XPATH, "/html/body/div/div/div[2]/div/div/div[5]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div")
    POLICY_FILE_UPLOAD = (By.ID, "file-upload-drag-and-drop-upload-policy-file")
    ADD_POLICY = (By.ID, "add-policy-button")
    UPDATE_POLICY = (By.ID, "accordian-0-header")
    UPDATE_POLICY_NAME_FIELD = (By.ID, "0-policyName-update")
    UPDATE_POLICY_DESCRIPTION_FIELD = (By.XPATH, "//div[@id='0-accordian-detail']//div//div[@aria-label='Description']")
    UPDATE_POLICY_FILE_UPLOAD = (By.ID,"file-upload-drag-and-drop-0-file-update")
    UPDATE_CLOSE_BUTTON = (By.ID, "1-cancel-uploaded-file-icon")
    UPDATE_SAVE_BUTTON = (By.ID, "save-button-policy")
    UPDATE_POLICY_DELETE_ICON = (By.ID, "0delete-icon")
    UPDATE_POLICY_DELETE_POPPER = (By.ID, "0-delete-popper-accordian-button")
    UPDATE_POLICY_DELETE_POPPER2 = (By.ID,"0-delete-popper-policy-button")
    UPDATE_POLICY_DELETE_BUTTON2 = (By.ID,"delete-button-policy")
    CATEGORY_TAB = (By.ID, "category-settings-4")
    ADD_NEW_CATEGORY = (By.ID, "addnew-category-button")
    CATEGORY_NAME_FIELD = (By.ID, "categoryName")
    CATEGORY_DESCRIPTION_FIELD = (By.ID, "category_description")
    ADD_CATEGORY_BUTTON = (By.ID, "add-category-button")
    UPDATE_CATEGORY_ACCORDION = (By.ID, "accordian-0-header")
    UPDATE_CATEGORY_ACCORDION3 = (By.ID,"accordian-2-header")
    ADD_SUB_CATEGORY_NAME_FIELD = (By.ID, "each_subcategory")
    ADD_SUB_CATEGORY_ICON = (By.ID, "add-sub-category-button")
    SUB_CATEGORY_DELETE_BUTTON = (By.ID, "delete4-sub-category")
    UPDATE_CATEGORY_EDIT_ICON = (By.ID, "0edit-icon")
    EDIT_CATEGORY_NAME_FIELD = (By.ID, "edit-0-head-accordian-name")
    UPDATE_CATEGORY_NAME_BUTTON = (By.ID,"edit-0-button-datapoint")
    UPDATE_CATEGORY_DELETE_ICON = (By.ID, "2delete-icon")
    UPDATE_CATEGORY_POPPER_BUTTON_2 = (By.ID, "2-delete-popper-accordian-button")
    DELETE_CATEGORY_BUTTON = (By.ID,"delete-4-button-datapoint")
    CATEGORY_SUBMIT_BUTTON = (By.ID, "submit-button-category")
    CANCEL_BUTTON_CATEGORY = (By.ID,"cancel-button-category")
    DATAPOINT_TAB = (By.ID, "datapoint-settings-5")
    DATAPOINT_CATEGORY_NAME_FIELD = (By.ID, "datapoint-name-input-box-id")
    DATAPOINT_CATEGORY_DESCRIPTION_FIELD = (By.ID, "datapoint-name-input-box-description-id")
    DATAPOINT_CATEGORY_ADD_BUTTON = (By.ID, "add-datapoint-button")
    DATAPOINT_CATEGORY_SUBMIT_BUTTON = (By.ID, "addte-add-datapoint-button")
    UPDATE_DATAPOINT_CATEGORY = (By.ID, "datapoint-category-4-accordian")
    ADD_DATAPOINT_ATTRIBUTE_NAME_FIELD = (By.ID, "datapoint-attribute-4-input-box-id")
    ADD_DATAPOINT_ATTRIBUTE_ICON = (By.XPATH, "//div[@class='MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-c4sutr']//img[@id='add-subcategories-button']")
    DELETE_DATA_POINT_ATTRIBUTE_ICON =(By.XPATH,"//div[@class='MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-c4sutr']//button[@id='delete-1-datapoint-attribute']")
    EDIT_DATAPOINT_CATEGORY_NAME_FIELD = (By.ID, "datapoint-4-name-input-edit")
    UPDATE_DATAPOINT_CATEGORY_NAME_BUTTON = (By.ID, "update-0-button-category")
    UPDATE_DATAPOINT_CATEGORY_EDIT_BUTTON = (By.ID, "edit-4-button-datapoint")
    UPDATE_DATAPOINT_CATEGORY_UPDATE_BUTTON = (By.ID,"edit-4-button-datapoint")
    DELETE_DATA_POINT_CATEGORY_ICON = (By.ID,"delete-4-datapoint")
    DELETE_DATAPOINT_CATEGORY = (By.ID, "delete-4-button-datapoint")
    DELETE_DATAPOINT_CATEGORY_POPPER_BUTTON = (By.ID, "4-delete-popper-datapoint-button")
    SIGN_OUT_BUTTON = (By.ID,"navbar-signout")

    def __init__(self, driver):
        super().__init__(driver)

    """ These are the page actions for the Home_page"""

    def test_update_account_settings_page(self):
        self.do_click(self.FIRST_NAME_FIELD)
        self.do_select_all(self.FIRST_NAME_FIELD)
        self.do_clear(self.FIRST_NAME_FIELD)
        self.do_sendkeys(self.FIRST_NAME_FIELD, Testdata.ACCOUNT_FIRST_NAME)
        self.do_click(self.LAST_NAME_FIELD)
        self.do_select_all(self.LAST_NAME_FIELD)
        self.do_clear(self.LAST_NAME_FIELD)
        self.do_sendkeys(self.LAST_NAME_FIELD, Testdata.ACCOUNT_LAST_NAME)
        self.do_click(self.SELECT_COUNTRY_FLAG)
        self.do_click(self.CONTACT_NUMBER_FIELD)
        self.do_clear(self.CONTACT_NUMBER_FIELD)
        self.do_sendkeys(self.CONTACT_NUMBER_FIELD, Testdata.CONTACT_NUMBER)
        self.do_click(self.SUBMIT_BUTTON)

    def test_update_organization_settings_page(self):
        self.do_click(self.ORGANIZATION_SETTINGS_TAB)
        self.do_click(self.ORGANIZATION_NAME_FIELD)
        self.do_select_all(self.ORGANIZATION_NAME_FIELD)
        self.do_clear(self.ORGANIZATION_NAME_FIELD)
        self.do_click(self.ORGANIZATION_EMAIL_FIELD)
        self.do_select_all(self.ORGANIZATION_EMAIL_FIELD)
        self.do_clear(self.ORGANIZATION_EMAIL_FIELD)
        self.do_click(self.ORGANIZATION_WEBSITE_LINK_FIELD)
        self.do_select_all(self.ORGANIZATION_WEBSITE_LINK_FIELD)
        self.do_clear(self.ORGANIZATION_WEBSITE_LINK_FIELD)
        self.do_click(self.ORGANIZATION_CONTACTNUMBER_FIELD)
        self.do_clear(self.ORGANIZATION_CONTACTNUMBER_FIELD)
        self.do_click(self.COUNTRY_FIELD)
        self.do_click(self.SELECT_COUNTRY)
        self.do_click(self.ORGANIZATION_PINCODE_FIELD)
        self.do_clear(self.ORGANIZATION_PINCODE_FIELD)
        self.do_click(self.ORGANIZATION_DESCRIPTION_FIELD)
        self.do_select_all(self.ORGANIZATION_DESCRIPTION_FIELD)
        self.do_clear(self.ORGANIZATION_DESCRIPTION_FIELD)
        self.do_click(self.ORGANIZATION_SUBMIT_BUTTON)

    def test_add_policy(self):
        self.do_click(self.POLICY_TAB)
        self.do_click(self.ADD_NEW_POLICY)
        self.do_click(self.POLICY_DESCRIPTION)
        self.do_sendkeys(self.POLICY_DESCRIPTION, Testdata.POLICY_DESCRIPTION)
        self.do_click(self.ADD_POLICY)

    def test_update_policy(self):
        self.do_click(self.UPDATE_POLICY)
        self.do_click(self.UPDATE_POLICY_NAME_FIELD)
        self.do_select_all(self.UPDATE_POLICY_NAME_FIELD)
        self.do_clear(self.UPDATE_POLICY_NAME_FIELD)
        self.do_sendkeys(self.UPDATE_POLICY_NAME_FIELD, Testdata.UPDATE_POLICY_NAME)
        self.do_click(self.UPDATE_POLICY_DESCRIPTION_FIELD)
        self.do_select_all(self.UPDATE_POLICY_DESCRIPTION_FIELD)
        self.do_clear(self.UPDATE_POLICY_DESCRIPTION_FIELD)
        self.do_sendkeys(self.UPDATE_POLICY_DESCRIPTION_FIELD, Testdata.UPDATE_POLICY_DESCRIPTION)
        self.do_click(self.UPDATE_SAVE_BUTTON)


    def test_add_category(self):
        self.do_click(self.CATEGORY_TAB)
        self.do_click(self.ADD_NEW_CATEGORY)
        self.do_click(self.CATEGORY_NAME_FIELD)
        self.do_sendkeys(self.CATEGORY_NAME_FIELD, Testdata.CATEGORY_NAME)
        self.do_click(self.CATEGORY_DESCRIPTION_FIELD)
        self.do_sendkeys(self.CATEGORY_DESCRIPTION_FIELD, Testdata.CATEGORY_DESCRIPTION)
        self.do_click(self.ADD_CATEGORY_BUTTON)

    def test_update_categories(self):
        self.do_click(self.UPDATE_CATEGORY_ACCORDION)
        self.do_click(self.ADD_SUB_CATEGORY_NAME_FIELD)
        self.do_sendkeys(self.ADD_SUB_CATEGORY_NAME_FIELD, Testdata.ADD_SUB_CATEGORY_NAME)
        self.do_click(self.ADD_SUB_CATEGORY_ICON)
        self.do_click(self.CATEGORY_SUBMIT_BUTTON)

    def test_adding_datapoint(self):
        self.do_click(self.DATAPOINT_TAB)
        self.do_click(self.DATAPOINT_CATEGORY_NAME_FIELD)
        self.do_sendkeys(self.DATAPOINT_CATEGORY_NAME_FIELD, Testdata.DATAPOINT_CATEGORY_NAME)
        self.do_click(self.DATAPOINT_CATEGORY_DESCRIPTION_FIELD)
        self.do_sendkeys(self.DATAPOINT_CATEGORY_DESCRIPTION_FIELD, Testdata.DATAPOINT_CATEGORY_DESCRIPTION)
        self.do_click(self.DATAPOINT_CATEGORY_ADD_BUTTON)
        self.do_click(self.DATAPOINT_CATEGORY_SUBMIT_BUTTON)

    def test_update_Datapoint_attributes(self):
        self.do_click(self.UPDATE_DATAPOINT_CATEGORY)
        self.do_click(self.ADD_DATAPOINT_ATTRIBUTE_NAME_FIELD)
        self.do_sendkeys(self.ADD_DATAPOINT_ATTRIBUTE_NAME_FIELD, Testdata.ADD_DATAPOINT_ATTRIBUTES)
        self.do_click(self.ADD_DATAPOINT_ATTRIBUTE_ICON)
        self.do_click(self.DATAPOINT_CATEGORY_SUBMIT_BUTTON)
        self.do_click(self.UPDATE_DATAPOINT_CATEGORY_EDIT_BUTTON)
        self.do_click(self.EDIT_DATAPOINT_CATEGORY_NAME_FIELD)
        self.do_select_all(self.EDIT_DATAPOINT_CATEGORY_NAME_FIELD)
        self.do_clear(self.EDIT_DATAPOINT_CATEGORY_NAME_FIELD)
        self.do_sendkeys(self.EDIT_DATAPOINT_CATEGORY_NAME_FIELD, Testdata.UPDATED_DATAPOINT_CATEGORY_NAME)
        self.do_click(self.UPDATE_DATAPOINT_CATEGORY_NAME_BUTTON)
        self.do_click(self.DATAPOINT_CATEGORY_SUBMIT_BUTTON)
        self.do_click(self.DELETE_DATAPOINT_CATEGORY)
        self.do_click(self.DELETE_DATAPOINT_CATEGORY_2)
